import pyQChem as qc
rem=qc.rem_array()
rem.basis("sto-3g")
xyz=qc.cartesian()
xyz.add_atom()
xyz.add_atom("H","0","0",".74")
molec=qc.mol_array(xyz)
job=qc.inputfile()
job.add(rem)
job.add(molec)
job.write("h2.in")
